services:
    app:
        image: laravelsail/php83
        container_name: laravel_api_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-api-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
